// <auto-generated />
using System;
using EfcToXamarinAndroid.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcToXamarinAndroid.MigrationsHelper.Migrations
{
    [DbContext(typeof(DataItemContext))]
    partial class DataItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EfcToXamarinAndroid.Core.DataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("CastomCategoryTyps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCategoryTyps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripton")
                        .HasColumnType("TEXT");

                    b.Property<long>("HashId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsParent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Karta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MCC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MccDeskription")
                        .HasColumnType("TEXT");

                    b.Property<float>("OldSum")
                        .HasColumnType("REAL");

                    b.Property<int>("OperacionTyp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmsAdress")
                        .HasColumnType("TEXT");

                    b.Property<float>("Sum")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnreachableOperacionTyp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnreachableText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("OperacionTyp");

                    b.ToTable("Cats");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EripPayerNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopInn")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalSum")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DataItemId")
                        .IsUnique();

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.ReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Sum")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.SybCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DataItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataItemId");

                    b.ToTable("SybCategory");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.Receipt", b =>
                {
                    b.HasOne("EfcToXamarinAndroid.Core.DataItem", "DataItem")
                        .WithOne("Receipt")
                        .HasForeignKey("EfcToXamarinAndroid.Core.Receipt", "DataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataItem");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.ReceiptItem", b =>
                {
                    b.HasOne("EfcToXamarinAndroid.Core.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.SybCategory", b =>
                {
                    b.HasOne("EfcToXamarinAndroid.Core.DataItem", null)
                        .WithMany("SubCategorys")
                        .HasForeignKey("DataItemId");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.DataItem", b =>
                {
                    b.Navigation("Receipt");

                    b.Navigation("SubCategorys");
                });

            modelBuilder.Entity("EfcToXamarinAndroid.Core.Receipt", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
