<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    
    <!-- Отключаем Brotli сжатие для избежания ошибки DOTNET_HOST_PATH -->
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="8.15.0" />
    <PackageReference Include="MudBlazor.ThemeManager" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EfcToXamarinAndroid\EfcToXamarinAndroid.Core.csproj" />
    <ProjectReference Include="..\EfcToXamarinAndroid.UI\EfcToXamarinAndroid.UI.csproj" />
  </ItemGroup>

</Project>
